telegram:
  token: "telegram bot token" # telegram bot token
  chat: -100123123
  topics: # optional, if u use telegram chat as a forum
     container-name-1: 41
     container-name-2: 38
     container-name-3: 22
     container-name-4: 19
     container-name-5: 56



kube:
  config: "/users/home/developer/.kube/config" # path to kube config 
  namespace: "kube_namespace"
  replacements:
  - target: '\bBearer eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\b'
    replacement: "_"
  filter: # filter for logs, support regexp (only rows containing these filters will be sent)
    - '.*"level":"error".*'
    - '.*panic.*'
  target:
    - pod: "^pod-name-1-production-*" # pod name, also support regexp
      container: # container names
        - "container-name-1" 
        - "container-name-2" 
        - "container-name-3" 
        - "container-name-4" 
    - pod: "^pod-name-2-production-*" 
      container:
        - "container-name-5" 
